services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    # command: flask --app app.py --debug run --port 5000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/myapp
      - WORKER_URI=http://worker:5001
    volumes:
      - ./api:/app

  worker:
    build: ./worker
    ports:
      - "5001:5001"
    # command: flask --app app.py --debug run --port 5001
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/myapp
    volumes:
      - ./worker:/app

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data:
